services:
  postgres:
    image: postgres:13
    container_name: sysml2-postgres
    environment:
      POSTGRES_DB: sysml2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sysml-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sysml2"]
      interval: 10s
      timeout: 5s
      retries: 5

  sysml-api:
    build: .
    container_name: sysml2-api
    ports:
      - "9000:9000"
    environment:
      # Database configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sysml2
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      # Play framework configuration
      PLAY_HTTP_SECRET_KEY: "sysml2-docker-secret-key-change-in-production"
      JAVA_OPTS: "-Xmx1024m -Xms512m"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sysml-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  sysml-network:
    driver: bridge